server:
  port: 8080
spring:
  application:
    name: MQDemoApplication
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

